# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=10, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('identity', models.CharField(default='', max_length=20, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('bank', models.CharField(default='', max_length=20, verbose_name='\u5f00\u6237\u884c')),
                ('bank_number', models.CharField(default='', max_length=30, verbose_name='\u94f6\u884c\u5361\u53f7')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6)),
                ('address', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='users/default.png', upload_to='users/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5b8c\u5584\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u5b8c\u5584\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserMust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7528\u6237ID')),
                ('password', models.CharField(default='', max_length=20, verbose_name='\u5bc6\u7801')),
                ('nick_name', models.CharField(default='', max_length=20, verbose_name='\u6635\u79f0')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserSelectable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=20, verbose_name='\u6635\u79f0')),
                ('education', models.CharField(default='', max_length=20, verbose_name='\u5b66\u5386')),
                ('qq', models.CharField(default='', max_length=20, verbose_name='QQ\u53f7')),
                ('wechat', models.CharField(default='', max_length=30, verbose_name='\u5fae\u4fe1\u53f7')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMust', verbose_name='\u7528\u6237ID')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53ef\u9009\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u53ef\u9009\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='usercomplete',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMust', verbose_name='\u7528\u6237ID'),
        ),
    ]
