# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equip_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_picture',
            field=models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_type',
            field=models.CharField(choices=[('Equipment', '\u8bbe\u5907'), ('Software', '\u8f6f\u4ef6'), ('Technology', '\u6280\u672f')], max_length=10, verbose_name='\u6700\u521d\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_image',
            field=models.CharField(max_length=100, verbose_name='\u8f6f\u4ef6\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_type',
            field=models.CharField(choices=[('Equipment', '\u8bbe\u5907'), ('Software', '\u8f6f\u4ef6'), ('Technology', '\u6280\u672f')], max_length=10, verbose_name='\u6700\u521d\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='tech_image',
            field=models.CharField(max_length=100, verbose_name='\u6280\u672f\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='tech_type',
            field=models.CharField(choices=[('Equipment', '\u8bbe\u5907'), ('Software', '\u8f6f\u4ef6'), ('Technology', '\u6280\u672f')], max_length=10, verbose_name='\u6700\u521d\u5206\u7c7b'),
        ),
    ]
