# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Things', '0002_auto_20180308_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equip_id',
            field=models.IntegerField(db_column='equip_id', primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_id',
            field=models.IntegerField(db_column='software_id', primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID'),
        ),
    ]
