# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Things', '0004_auto_20180308_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_type',
            name='type_id1',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907\u5206\u7c7bID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID'),
        ),
    ]
