# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-09 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_type', models.CharField(choices=[('equipment', '\u8bbe\u5907'), ('software', '\u8f6f\u4ef6'), ('technology', '\u6280\u672f')], default='equipment', max_length=3, verbose_name='\u4ea7\u54c1\u6700\u521d\u5206\u7c7b')),
                ('product_id', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4ea7\u54c1ID')),
                ('product_image', models.ImageField(default='product/default.png', upload_to='product/%Y/%m', verbose_name='\u6536\u85cf\u4ea7\u54c1\u56fe\u7247')),
                ('product_name', models.CharField(max_length=30, verbose_name='\u6536\u85cf\u4ea7\u54c1\u540d\u79f0')),
                ('product_price', models.FloatField(default=0, verbose_name='\u8d39\u7528')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMust', verbose_name='\u7528\u6237ID')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('equipment', '\u8bbe\u5907'), ('software', '\u8f6f\u4ef6'), ('technology', '\u6280\u672f')], default='equipment', max_length=3, verbose_name='\u4ea7\u54c1\u6700\u521d\u5206\u7c7b')),
                ('product_id', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u4ea7\u54c1ID')),
                ('issue_image', models.ImageField(default='product/default.png', upload_to='product/%Y/%m', verbose_name='\u53d1\u5e03\u4ea7\u54c1\u56fe\u7247')),
                ('product_name', models.CharField(max_length=30, verbose_name='\u53d1\u5e03\u4ea7\u54c1\u540d\u79f0')),
                ('issue_price', models.FloatField(default=0, verbose_name='\u8d39\u7528')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMust', verbose_name='\u7528\u6237ID')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53d1\u5e03',
                'verbose_name_plural': '\u7528\u6237\u53d1\u5e03',
            },
        ),
    ]
